[versions]
activity-compose = "1.9.1"
appcompat = "1.7.0"
cardview = "1.0.0"
circleimageview = "3.1.0"
compact-calendar-view = "3.0.0"
compose-bom = "2024.11.00"
constraintlayout = "2.1.4"
core-ktx = "1.13.1"
core-splashscreen = "1.0.1"
credentials = "1.2.2"
custom-google-signin-button = "2.0.0"
espresso-core = "3.6.1"
facebook-android-sdk = "13.0.0"
firebase-analytics = "22.0.2"
firebase-appcheck-safetynet = "16.1.2"
firebase-auth = "23.0.0"
firebase-bom = "33.1.2"
firebase-core = "21.1.1"
firebase-storage = "21.0.0"
firebase-ui-auth = "8.0.0"
glide-compiler = "4.12.0"
googleid = "1.1.1"
hilt-android = "2.52"
hilt-compiler = "1.2.0"
hilt-lifecycle-viewmodel = "1.0.0-alpha03"
hilt-navigation-compose = "1.2.0"
junit = "1.2.1"
kotlin = "2.0.20"
kotlinx-coroutines-play-services = "1.6.4"
ksp = "2.0.20-1.0.25"
lifecycle-viewmodel = "2.8.4"
logging-interceptor = "4.7.2"
material = "1.12.0"
material-calendar-view = "1.9.2"
material-version = "1.6.1"
navigation = "2.8.1"
agp = "8.5.2"
google-services = "4.4.2"
play-services-auth = "21.2.0"
recyclerview = "1.3.2"
retrofit = "2.9.0"
room-runtime = "2.6.1"
tedpermission-normal = "3.4.2"
work-runtime-ktx = "2.9.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-hilt-lifecycle-viewmodel = { module = "androidx.hilt:hilt-lifecycle-viewmodel", version.ref = "hilt-lifecycle-viewmodel" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-viewmodel" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
compact-calendar-view = { module = "com.github.sundeepk:compact-calendar-view", version.ref = "compact-calendar-view" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide-compiler" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
custom-google-signin-button = { module = "com.github.shobhitpuri:custom-google-signin-button", version.ref = "custom-google-signin-button" }
facebook-android-sdk = { module = "com.facebook.android:facebook-android-sdk", version.ref = "facebook-android-sdk" }
firebase-ads = { module = "com.google.firebase:firebase-ads", version.ref = "firebase-storage" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-appcheck-safetynet = { module = "com.google.firebase:firebase-appcheck-safetynet", version.ref = "firebase-appcheck-safetynet" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-core = { module = "com.google.firebase:firebase-core", version.ref = "firebase-core" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebase-storage" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase-auth" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebase-storage" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebase-ui-auth" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide-compiler" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines-play-services" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-calendar-view = { module = "com.applandeo:material-calendar-view", version.ref = "material-calendar-view" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
tedpermission-normal = { module = "io.github.ParkSangGwon:tedpermission-normal", version.ref = "tedpermission-normal" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp"}
koltin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
navigation-saafeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android"}
google-servies = { id = "com.google.gms.google-services", version.ref = "google-services"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }